In [1]:
# example making new class predictions for a classification problem
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from random import randint
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from keras.utils import np_utils

Using TensorFlow backend.
/home/greed/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/greed/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/greed/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])

In [2]:
# https://machinelearningmastery.com/how-to-make-classification-and-regression-predictions-for-deep-learning-models-in-keras/
# example making new class predictions for a classification problem
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import MinMaxScaler

def work():
    # generate 2d classification dataset
    X, y = make_blobs(n_samples=100, centers=2, n_features=2, random_state=1)
    scalar = MinMaxScaler()
    scalar.fit(X)
    X = scalar.transform(X)
    # define and fit the final model
    model = Sequential()
    model.add(Dense(4, input_dim=2, activation='relu'))
    model.add(Dense(4, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    model.fit(X, y, epochs=500, verbose=0)
    # new instances where we do not know the answer
    Xnew, _ = make_blobs(n_samples=3, centers=2, n_features=2, random_state=1)
    Xnew = scalar.transform(Xnew)
    # make a prediction
    ynew = model.predict_classes(Xnew)
    # show the inputs and predicted outputs
    for i in range(len(Xnew)):
        print("X=%s, Predicted=%s" % (Xnew[i], ynew[i]))

# CLASSIFICATION PART

In [3]:
def generate():
    seq=0
    max_len=190
    q=0
    x=[]
    y=[]
    for i in range(seq, max_len):
        r = randint(0, 9)
        if i%50==0: q+=1
        if q>=10: q=0
        rnd_line = [randint(0, 9) for _ in range(3)]
        rnd_line = np.append(q, rnd_line)
        rnd_line = np.append(q, rnd_line)
        rnd_line = np.append(q, rnd_line)
        x.append(rnd_line)
        #print(rnd_line)
        y.append(q)
    x = pd.DataFrame(x).values
    return x, y

X, y = generate()
print(X)
X_base = np.array([])
for i in range(len(X)):
    #print(X[i])
    X_base=np.append(X_base,X[i])

[[1 1 1 2 6 2]
 [1 1 1 2 8 7]
 [1 1 1 2 1 9]
 ...
 [4 4 4 5 8 5]
 [4 4 4 7 7 0]
 [4 4 4 5 1 5]]


In [7]:
#https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(8, input_dim=6, activation='relu'))
	model.add(Dense(4, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

estimator = KerasClassifier(build_fn=baseline_model, epochs=500, batch_size=5, verbose=1)

kfold = KFold(n_splits=10, shuffle=True)
#results = cross_val_score(estimator, X, dummy_y, cv=kfold)
estimator.fit(X, dummy_y)

#estimator = KerasClassifier(build_fn=SS.create_model, nb_epoch=10, verbose=0)
#estimator = KerasClassifier(build_fn=model, epochs=200, batch_size=5, verbose=1)
#kfold = KFold(n_splits=10, shuffle=True)
#
#results = cross_val_score(estimator, X, dummy_y, cv=kfold)

#print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/500
190/190 [==============================] - 1s 7ms/step - loss: 2.4475 - acc: 0.2105
Epoch 2/500
190/190 [==============================] - 0s 395us/step - loss: 1.8358 - acc: 0.2000
Epoch 3/500
190/190 [==============================] - 0s 377us/step - loss: 1.5970 - acc: 0.2632
Epoch 4/500
190/190 [==============================] - 0s 375us/step - loss: 1.4747 - acc: 0.3105
Epoch 5/500
190/190 [==============================] - 0s 376us/step - loss: 1.4086 - acc: 0.3579
Epoch 6/500
190/190 [==============================] - 0s 354us/step - loss: 1.3440 - acc: 0.3684
Epoch 7/500
190/190 [==============================] - 0s 355us/step - loss: 1.2928 - acc: 0.4000
Epoch 8/500
190/190 [==============================] - 0s 365us/step - loss: 1.2551 - acc: 0.3947
Epoch 9/500
190/190 [==============================] - 0s 354us/step - loss: 1.2186 - acc: 0.4158
Epoch 10/500
190/190

190/190 [==============================] - 0s 353us/step - loss: 0.6305 - acc: 0.7421
Epoch 68/500
190/190 [==============================] - 0s 363us/step - loss: 0.6257 - acc: 0.7316
Epoch 69/500
190/190 [==============================] - 0s 365us/step - loss: 0.6210 - acc: 0.7263
Epoch 70/500
190/190 [==============================] - 0s 356us/step - loss: 0.6175 - acc: 0.7105
Epoch 71/500
190/190 [==============================] - 0s 355us/step - loss: 0.6182 - acc: 0.7368
Epoch 72/500
190/190 [==============================] - 0s 358us/step - loss: 0.6103 - acc: 0.7421
Epoch 73/500
190/190 [==============================] - 0s 355us/step - loss: 0.6054 - acc: 0.7368
Epoch 74/500
190/190 [==============================] - 0s 358us/step - loss: 0.6003 - acc: 0.7474
Epoch 75/500
190/190 [==============================] - 0s 356us/step - loss: 0.5977 - acc: 0.7316
Epoch 76/500
190/190 [==============================] - 0s 363us/step - loss: 0.5944 - acc: 0.7316
Epoch 77/500
190/190 [=

190/190 [==============================] - 0s 357us/step - loss: 0.3437 - acc: 0.8895
Epoch 150/500
190/190 [==============================] - 0s 358us/step - loss: 0.3411 - acc: 0.8684
Epoch 151/500
190/190 [==============================] - 0s 358us/step - loss: 0.3387 - acc: 0.8737
Epoch 152/500
190/190 [==============================] - 0s 355us/step - loss: 0.3376 - acc: 0.8737
Epoch 153/500
190/190 [==============================] - 0s 354us/step - loss: 0.3318 - acc: 0.8789
Epoch 154/500
190/190 [==============================] - 0s 356us/step - loss: 0.3278 - acc: 0.8737
Epoch 155/500
190/190 [==============================] - 0s 358us/step - loss: 0.3247 - acc: 0.9053
Epoch 156/500
190/190 [==============================] - 0s 354us/step - loss: 0.3202 - acc: 0.9000
Epoch 157/500
190/190 [==============================] - 0s 359us/step - loss: 0.3186 - acc: 0.8737
Epoch 158/500
190/190 [==============================] - 0s 353us/step - loss: 0.3160 - acc: 0.9000
Epoch 159/500


190/190 [==============================] - 0s 358us/step - loss: 0.1180 - acc: 1.0000
Epoch 232/500
190/190 [==============================] - 0s 359us/step - loss: 0.1173 - acc: 1.0000
Epoch 233/500
190/190 [==============================] - 0s 362us/step - loss: 0.1143 - acc: 1.0000
Epoch 234/500
190/190 [==============================] - 0s 365us/step - loss: 0.1098 - acc: 1.0000
Epoch 235/500
190/190 [==============================] - 0s 353us/step - loss: 0.1081 - acc: 1.0000
Epoch 236/500
190/190 [==============================] - 0s 360us/step - loss: 0.1062 - acc: 1.0000
Epoch 237/500
190/190 [==============================] - 0s 352us/step - loss: 0.1042 - acc: 1.0000
Epoch 238/500
190/190 [==============================] - 0s 355us/step - loss: 0.1020 - acc: 1.0000
Epoch 239/500
190/190 [==============================] - 0s 356us/step - loss: 0.0997 - acc: 1.0000
Epoch 240/500
190/190 [==============================] - 0s 358us/step - loss: 0.0985 - acc: 1.0000
Epoch 241/500


190/190 [==============================] - 0s 359us/step - loss: 0.0277 - acc: 1.0000
Epoch 314/500
190/190 [==============================] - 0s 367us/step - loss: 0.0269 - acc: 1.0000
Epoch 315/500
190/190 [==============================] - 0s 361us/step - loss: 0.0267 - acc: 1.0000
Epoch 316/500
190/190 [==============================] - 0s 360us/step - loss: 0.0258 - acc: 1.0000
Epoch 317/500
190/190 [==============================] - 0s 358us/step - loss: 0.0255 - acc: 1.0000
Epoch 318/500
190/190 [==============================] - 0s 357us/step - loss: 0.0250 - acc: 1.0000
Epoch 319/500
190/190 [==============================] - 0s 361us/step - loss: 0.0243 - acc: 1.0000
Epoch 320/500
190/190 [==============================] - 0s 359us/step - loss: 0.0244 - acc: 1.0000
Epoch 321/500
190/190 [==============================] - 0s 357us/step - loss: 0.0237 - acc: 1.0000
Epoch 322/500
190/190 [==============================] - 0s 354us/step - loss: 0.0233 - acc: 1.0000
Epoch 323/500


190/190 [==============================] - 0s 358us/step - loss: 0.0064 - acc: 1.0000
Epoch 396/500
190/190 [==============================] - 0s 366us/step - loss: 0.0063 - acc: 1.0000
Epoch 397/500
190/190 [==============================] - 0s 353us/step - loss: 0.0062 - acc: 1.0000
Epoch 398/500
190/190 [==============================] - 0s 355us/step - loss: 0.0061 - acc: 1.0000
Epoch 399/500
190/190 [==============================] - 0s 354us/step - loss: 0.0060 - acc: 1.0000
Epoch 400/500
190/190 [==============================] - 0s 353us/step - loss: 0.0059 - acc: 1.0000
Epoch 401/500
190/190 [==============================] - 0s 357us/step - loss: 0.0058 - acc: 1.0000
Epoch 402/500
190/190 [==============================] - 0s 357us/step - loss: 0.0057 - acc: 1.0000
Epoch 403/500
190/190 [==============================] - 0s 355us/step - loss: 0.0055 - acc: 1.0000
Epoch 404/500
190/190 [==============================] - 0s 356us/step - loss: 0.0055 - acc: 1.0000
Epoch 405/500


190/190 [==============================] - 0s 355us/step - loss: 0.0015 - acc: 1.0000
Epoch 478/500
190/190 [==============================] - 0s 361us/step - loss: 0.0014 - acc: 1.0000
Epoch 479/500
190/190 [==============================] - 0s 359us/step - loss: 0.0014 - acc: 1.0000
Epoch 480/500
190/190 [==============================] - 0s 355us/step - loss: 0.0014 - acc: 1.0000
Epoch 481/500
190/190 [==============================] - 0s 360us/step - loss: 0.0014 - acc: 1.0000
Epoch 482/500
190/190 [==============================] - 0s 366us/step - loss: 0.0013 - acc: 1.0000
Epoch 483/500
190/190 [==============================] - 0s 357us/step - loss: 0.0013 - acc: 1.0000
Epoch 484/500
190/190 [==============================] - 0s 354us/step - loss: 0.0013 - acc: 1.0000
Epoch 485/500
190/190 [==============================] - 0s 359us/step - loss: 0.0012 - acc: 1.0000
Epoch 486/500
190/190 [==============================] - 0s 356us/step - loss: 0.0012 - acc: 1.0000
Epoch 487/500


In [45]:
import inspect
print(inspect.getfullargspec(estimator.fit))

X_test=np.array([1, 3, 3, 8, 1, 7]).reshape(1,6)
print('test:', X_test)

y_pred = estimator.predict( X_test )
print(y_pred)

FullArgSpec(args=['self', 'x', 'y', 'sample_weight'], varargs=None, varkw='kwargs', defaults=(None,), kwonlyargs=[], kwonlydefaults=None, annotations={})
test: [[1 3 3 8 1 7]]
1/1 [==============================] - 0s 17ms/step
[1]


In [9]:
from numpy import array
# one hot encode sequence
def one_hot_encode(sequence, n_unique=5):
	encoding = list()
	for value in sequence:
		vector = [0 for _ in range(n_unique)]
		vector[value] = 1
		encoding.append(vector)
	return array(encoding)

# decode a one hot encoded string
def one_hot_decode(encoded_seq):
	return [argmax(vector) for vector in encoded_seq]

In [10]:
y2=X1.drop(['y'], axis=1)
print(y2.values)
print('='*20)
x2=X1['y']
x2_enc=one_hot_encode(x2)
print(np.array(y2.values))
#y2_enc = one_hot_encode( [np.array(y2.values).astype(int)] )

[[1 1 1 2 9 7]
 [1 1 1 0 1 9]
 [1 1 1 7 9 7]
 ...
 [4 4 4 2 0 4]
 [4 4 4 6 1 1]
 [4 4 4 1 4 0]]
[[1 1 1 2 9 7]
 [1 1 1 0 1 9]
 [1 1 1 7 9 7]
 ...
 [4 4 4 2 0 4]
 [4 4 4 6 1 1]
 [4 4 4 1 4 0]]


# LSTM PART

In [38]:
from random import randint
from numpy import array
from numpy import argmax
from pandas import concat
from pandas import DataFrame
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

# one hot encode sequence
def one_hot_encode(sequence, n_unique=10):
	encoding = list()
	for value in sequence:
		vector = [0 for _ in range(n_unique)]
		vector[value] = 1
		encoding.append(vector)
	return array(encoding)

# decode a one hot encoded string
def one_hot_decode(encoded_seq):
	return [argmax(vector) for vector in encoded_seq]

def generate(i):
    ln = 20
    a0=X_base[i+0:i+0+ln]
    a1=X_base[i+1:i+1+ln]
    a2=X_base[i+2:i+2+ln]
    a3=X_base[i+3:i+3+ln]
    a4=X_base[i+4:i+4+ln]
    
    a0 = a0.astype(int)
    a1 = a1.astype(int)
    a2 = a2.astype(int)
    a3 = a3.astype(int)
    a4 = a4.astype(int)
    
    e0=DataFrame(one_hot_encode(a0.tolist()))
    e1=DataFrame(one_hot_encode(a1.tolist()))
    e2=DataFrame(one_hot_encode(a2.tolist()))
    e3=DataFrame(one_hot_encode(a3.tolist()))
    e4=DataFrame(one_hot_encode(a4.tolist()))
    ea=concat([e0, e1, e2, e3, e4], axis=1)
    ea=ea.values
    # convert to 3d for input
    X = ea.reshape( len(ea), 5, 10 )
    ##print(a0, a1, a2, a3, a4)
    y = one_hot_encode(a4)
    return X, y
    #return None, None

In [42]:
# define model
model = Sequential()
model.add(LSTM(100, batch_input_shape=(5, 5, 10), stateful=True))
model.add(Dense(10, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [43]:
# fit model
for z in range(40):
    for i in range(180):
        print(z, i)
        X, y = generate(i)
        #print('decode',one_hot_decode(X[0]))
        #print('decode',one_hot_decode(X[1]))
        #print('decode',one_hot_decode(X[2]))
        #print('decode',one_hot_decode(X[3]))
        #print('decode',one_hot_decode(X[4]))
        #print('dec y:',one_hot_decode(y))

        model.fit(X, y, epochs=1, batch_size=5, verbose=2, shuffle=False)
        model.reset_states()

0 0
Epoch 1/1
 - 1s - loss: 2.2774 - acc: 0.3000
0 1
Epoch 1/1
 - 0s - loss: 2.1640 - acc: 0.6500
0 2
Epoch 1/1
 - 0s - loss: 2.0116 - acc: 0.7000
0 3
Epoch 1/1
 - 0s - loss: 1.7819 - acc: 0.7000
0 4
Epoch 1/1
 - 0s - loss: 1.4182 - acc: 0.7000
0 5
Epoch 1/1
 - 0s - loss: 1.4031 - acc: 0.6500
0 6
Epoch 1/1
 - 0s - loss: 1.3837 - acc: 0.7000
0 7
Epoch 1/1
 - 0s - loss: 1.1748 - acc: 0.7500
0 8
Epoch 1/1
 - 0s - loss: 0.9944 - acc: 0.8000
0 9
Epoch 1/1
 - 0s - loss: 0.8375 - acc: 0.8000
0 10
Epoch 1/1
 - 0s - loss: 1.1158 - acc: 0.7500
0 11
Epoch 1/1
 - 0s - loss: 1.2526 - acc: 0.7000
0 12
Epoch 1/1
 - 0s - loss: 1.4006 - acc: 0.7000
0 13
Epoch 1/1
 - 0s - loss: 1.3132 - acc: 0.7000
0 14
Epoch 1/1
 - 0s - loss: 1.1762 - acc: 0.7500
0 15
Epoch 1/1
 - 0s - loss: 1.1336 - acc: 0.7500
0 16
Epoch 1/1
 - 0s - loss: 1.1667 - acc: 0.7000
0 17
Epoch 1/1
 - 0s - loss: 1.2529 - acc: 0.6500
0 18
Epoch 1/1
 - 0s - loss: 1.2673 - acc: 0.6500
0 19
Epoch 1/1
 - 0s - loss: 1.1913 - acc: 0.6500
0 20
Epoch

0 163
Epoch 1/1
 - 0s - loss: 0.5682 - acc: 0.9500
0 164
Epoch 1/1
 - 0s - loss: 0.4858 - acc: 0.9500
0 165
Epoch 1/1
 - 0s - loss: 0.4618 - acc: 0.9500
0 166
Epoch 1/1
 - 0s - loss: 0.5672 - acc: 0.9000
0 167
Epoch 1/1
 - 0s - loss: 0.5926 - acc: 0.9000
0 168
Epoch 1/1
 - 0s - loss: 0.6400 - acc: 0.8500
0 169
Epoch 1/1
 - 0s - loss: 0.5680 - acc: 0.8500
0 170
Epoch 1/1
 - 0s - loss: 0.4976 - acc: 0.9000
0 171
Epoch 1/1
 - 0s - loss: 0.4879 - acc: 0.9500
0 172
Epoch 1/1
 - 0s - loss: 0.5599 - acc: 0.9000
0 173
Epoch 1/1
 - 0s - loss: 0.5904 - acc: 0.9000
0 174
Epoch 1/1
 - 0s - loss: 0.5918 - acc: 0.9000
0 175
Epoch 1/1
 - 0s - loss: 0.5221 - acc: 1.0000
0 176
Epoch 1/1
 - 0s - loss: 0.4458 - acc: 1.0000
0 177
Epoch 1/1
 - 0s - loss: 0.4179 - acc: 1.0000
0 178
Epoch 1/1
 - 0s - loss: 0.4890 - acc: 0.9500
0 179
Epoch 1/1
 - 0s - loss: 0.5827 - acc: 0.9000
1 0
Epoch 1/1
 - 0s - loss: 0.7725 - acc: 0.8000
1 1
Epoch 1/1
 - 0s - loss: 0.6323 - acc: 0.8000
1 2
Epoch 1/1
 - 0s - loss: 0.4474 

1 146
Epoch 1/1
 - 0s - loss: 0.1173 - acc: 1.0000
1 147
Epoch 1/1
 - 0s - loss: 0.1168 - acc: 1.0000
1 148
Epoch 1/1
 - 0s - loss: 0.1205 - acc: 1.0000
1 149
Epoch 1/1
 - 0s - loss: 0.1500 - acc: 1.0000
1 150
Epoch 1/1
 - 0s - loss: 0.1410 - acc: 1.0000
1 151
Epoch 1/1
 - 0s - loss: 0.1272 - acc: 1.0000
1 152
Epoch 1/1
 - 0s - loss: 0.1061 - acc: 1.0000
1 153
Epoch 1/1
 - 0s - loss: 0.1000 - acc: 1.0000
1 154
Epoch 1/1
 - 0s - loss: 0.1071 - acc: 1.0000
1 155
Epoch 1/1
 - 0s - loss: 0.1099 - acc: 1.0000
1 156
Epoch 1/1
 - 0s - loss: 0.1080 - acc: 1.0000
1 157
Epoch 1/1
 - 0s - loss: 0.0953 - acc: 1.0000
1 158
Epoch 1/1
 - 0s - loss: 0.0864 - acc: 1.0000
1 159
Epoch 1/1
 - 0s - loss: 0.0835 - acc: 1.0000
1 160
Epoch 1/1
 - 0s - loss: 0.0884 - acc: 1.0000
1 161
Epoch 1/1
 - 0s - loss: 0.1517 - acc: 1.0000
1 162
Epoch 1/1
 - 0s - loss: 0.1525 - acc: 1.0000
1 163
Epoch 1/1
 - 0s - loss: 0.1320 - acc: 1.0000
1 164
Epoch 1/1
 - 0s - loss: 0.1109 - acc: 1.0000
1 165
Epoch 1/1
 - 0s - loss: 0

2 129
Epoch 1/1
 - 0s - loss: 0.0380 - acc: 1.0000
2 130
Epoch 1/1
 - 0s - loss: 0.0372 - acc: 1.0000
2 131
Epoch 1/1
 - 0s - loss: 0.0456 - acc: 1.0000
2 132
Epoch 1/1
 - 0s - loss: 0.0571 - acc: 1.0000
2 133
Epoch 1/1
 - 0s - loss: 0.0510 - acc: 1.0000
2 134
Epoch 1/1
 - 0s - loss: 0.0423 - acc: 1.0000
2 135
Epoch 1/1
 - 0s - loss: 0.0387 - acc: 1.0000
2 136
Epoch 1/1
 - 0s - loss: 0.0601 - acc: 1.0000
2 137
Epoch 1/1
 - 0s - loss: 0.0574 - acc: 1.0000
2 138
Epoch 1/1
 - 0s - loss: 0.0509 - acc: 1.0000
2 139
Epoch 1/1
 - 0s - loss: 0.0438 - acc: 1.0000
2 140
Epoch 1/1
 - 0s - loss: 0.0369 - acc: 1.0000
2 141
Epoch 1/1
 - 0s - loss: 0.0346 - acc: 1.0000
2 142
Epoch 1/1
 - 0s - loss: 0.0364 - acc: 1.0000
2 143
Epoch 1/1
 - 0s - loss: 0.0380 - acc: 1.0000
2 144
Epoch 1/1
 - 0s - loss: 0.0384 - acc: 1.0000
2 145
Epoch 1/1
 - 0s - loss: 0.0359 - acc: 1.0000
2 146
Epoch 1/1
 - 0s - loss: 0.0319 - acc: 1.0000
2 147
Epoch 1/1
 - 0s - loss: 0.0319 - acc: 1.0000
2 148
Epoch 1/1
 - 0s - loss: 0

3 112
Epoch 1/1
 - 0s - loss: 0.0141 - acc: 1.0000
3 113
Epoch 1/1
 - 0s - loss: 0.0151 - acc: 1.0000
3 114
Epoch 1/1
 - 0s - loss: 0.0171 - acc: 1.0000
3 115
Epoch 1/1
 - 0s - loss: 0.0154 - acc: 1.0000
3 116
Epoch 1/1
 - 0s - loss: 0.0145 - acc: 1.0000
3 117
Epoch 1/1
 - 0s - loss: 0.0141 - acc: 1.0000
3 118
Epoch 1/1
 - 0s - loss: 0.0144 - acc: 1.0000
3 119
Epoch 1/1
 - 0s - loss: 0.0143 - acc: 1.0000
3 120
Epoch 1/1
 - 0s - loss: 0.0137 - acc: 1.0000
3 121
Epoch 1/1
 - 0s - loss: 0.0125 - acc: 1.0000
3 122
Epoch 1/1
 - 0s - loss: 0.0108 - acc: 1.0000
3 123
Epoch 1/1
 - 0s - loss: 0.0103 - acc: 1.0000
3 124
Epoch 1/1
 - 0s - loss: 0.0116 - acc: 1.0000
3 125
Epoch 1/1
 - 0s - loss: 0.0122 - acc: 1.0000
3 126
Epoch 1/1
 - 0s - loss: 0.0180 - acc: 1.0000
3 127
Epoch 1/1
 - 0s - loss: 0.0165 - acc: 1.0000
3 128
Epoch 1/1
 - 0s - loss: 0.0145 - acc: 1.0000
3 129
Epoch 1/1
 - 0s - loss: 0.0135 - acc: 1.0000
3 130
Epoch 1/1
 - 0s - loss: 0.0138 - acc: 1.0000
3 131
Epoch 1/1
 - 0s - loss: 0

4 95
Epoch 1/1
 - 0s - loss: 0.0091 - acc: 1.0000
4 96
Epoch 1/1
 - 0s - loss: 0.0082 - acc: 1.0000
4 97
Epoch 1/1
 - 0s - loss: 0.0075 - acc: 1.0000
4 98
Epoch 1/1
 - 0s - loss: 0.0067 - acc: 1.0000
4 99
Epoch 1/1
 - 0s - loss: 0.0069 - acc: 1.0000
4 100
Epoch 1/1
 - 0s - loss: 0.0092 - acc: 1.0000
4 101
Epoch 1/1
 - 0s - loss: 0.0097 - acc: 1.0000
4 102
Epoch 1/1
 - 0s - loss: 0.0092 - acc: 1.0000
4 103
Epoch 1/1
 - 0s - loss: 0.0088 - acc: 1.0000
4 104
Epoch 1/1
 - 0s - loss: 0.0076 - acc: 1.0000
4 105
Epoch 1/1
 - 0s - loss: 0.0074 - acc: 1.0000
4 106
Epoch 1/1
 - 0s - loss: 0.0077 - acc: 1.0000
4 107
Epoch 1/1
 - 0s - loss: 0.0082 - acc: 1.0000
4 108
Epoch 1/1
 - 0s - loss: 0.0087 - acc: 1.0000
4 109
Epoch 1/1
 - 0s - loss: 0.0076 - acc: 1.0000
4 110
Epoch 1/1
 - 0s - loss: 0.0070 - acc: 1.0000
4 111
Epoch 1/1
 - 0s - loss: 0.0067 - acc: 1.0000
4 112
Epoch 1/1
 - 0s - loss: 0.0070 - acc: 1.0000
4 113
Epoch 1/1
 - 0s - loss: 0.0075 - acc: 1.0000
4 114
Epoch 1/1
 - 0s - loss: 0.0085

5 78
Epoch 1/1
 - 0s - loss: 0.0052 - acc: 1.0000
5 79
Epoch 1/1
 - 0s - loss: 0.0049 - acc: 1.0000
5 80
Epoch 1/1
 - 0s - loss: 0.0044 - acc: 1.0000
5 81
Epoch 1/1
 - 0s - loss: 0.0042 - acc: 1.0000
5 82
Epoch 1/1
 - 0s - loss: 0.0047 - acc: 1.0000
5 83
Epoch 1/1
 - 0s - loss: 0.0047 - acc: 1.0000
5 84
Epoch 1/1
 - 0s - loss: 0.0058 - acc: 1.0000
5 85
Epoch 1/1
 - 0s - loss: 0.0052 - acc: 1.0000
5 86
Epoch 1/1
 - 0s - loss: 0.0048 - acc: 1.0000
5 87
Epoch 1/1
 - 0s - loss: 0.0047 - acc: 1.0000
5 88
Epoch 1/1
 - 0s - loss: 0.0052 - acc: 1.0000
5 89
Epoch 1/1
 - 0s - loss: 0.0061 - acc: 1.0000
5 90
Epoch 1/1
 - 0s - loss: 0.0055 - acc: 1.0000
5 91
Epoch 1/1
 - 0s - loss: 0.0049 - acc: 1.0000
5 92
Epoch 1/1
 - 0s - loss: 0.0043 - acc: 1.0000
5 93
Epoch 1/1
 - 0s - loss: 0.0041 - acc: 1.0000
5 94
Epoch 1/1
 - 0s - loss: 0.0046 - acc: 1.0000
5 95
Epoch 1/1
 - 0s - loss: 0.0049 - acc: 1.0000
5 96
Epoch 1/1
 - 0s - loss: 0.0045 - acc: 1.0000
5 97
Epoch 1/1
 - 0s - loss: 0.0042 - acc: 1.0000


6 61
Epoch 1/1
 - 0s - loss: 0.0023 - acc: 1.0000
6 62
Epoch 1/1
 - 0s - loss: 0.0023 - acc: 1.0000
6 63
Epoch 1/1
 - 0s - loss: 0.0022 - acc: 1.0000
6 64
Epoch 1/1
 - 0s - loss: 0.0022 - acc: 1.0000
6 65
Epoch 1/1
 - 0s - loss: 0.0026 - acc: 1.0000
6 66
Epoch 1/1
 - 0s - loss: 0.0030 - acc: 1.0000
6 67
Epoch 1/1
 - 0s - loss: 0.0026 - acc: 1.0000
6 68
Epoch 1/1
 - 0s - loss: 0.0024 - acc: 1.0000
6 69
Epoch 1/1
 - 0s - loss: 0.0022 - acc: 1.0000
6 70
Epoch 1/1
 - 0s - loss: 0.0037 - acc: 1.0000
6 71
Epoch 1/1
 - 0s - loss: 0.0039 - acc: 1.0000
6 72
Epoch 1/1
 - 0s - loss: 0.0037 - acc: 1.0000
6 73
Epoch 1/1
 - 0s - loss: 0.0034 - acc: 1.0000
6 74
Epoch 1/1
 - 0s - loss: 0.0032 - acc: 1.0000
6 75
Epoch 1/1
 - 0s - loss: 0.0031 - acc: 1.0000
6 76
Epoch 1/1
 - 0s - loss: 0.0032 - acc: 1.0000
6 77
Epoch 1/1
 - 0s - loss: 0.0032 - acc: 1.0000
6 78
Epoch 1/1
 - 0s - loss: 0.0030 - acc: 1.0000
6 79
Epoch 1/1
 - 0s - loss: 0.0028 - acc: 1.0000
6 80
Epoch 1/1
 - 0s - loss: 0.0026 - acc: 1.0000


7 44
Epoch 1/1
 - 0s - loss: 0.0021 - acc: 1.0000
7 45
Epoch 1/1
 - 0s - loss: 0.0020 - acc: 1.0000
7 46
Epoch 1/1
 - 0s - loss: 0.0019 - acc: 1.0000
7 47
Epoch 1/1
 - 0s - loss: 0.0021 - acc: 1.0000
7 48
Epoch 1/1
 - 0s - loss: 0.0020 - acc: 1.0000
7 49
Epoch 1/1
 - 0s - loss: 0.0018 - acc: 1.0000
7 50
Epoch 1/1
 - 0s - loss: 0.0016 - acc: 1.0000
7 51
Epoch 1/1
 - 0s - loss: 0.0015 - acc: 1.0000
7 52
Epoch 1/1
 - 0s - loss: 0.0018 - acc: 1.0000
7 53
Epoch 1/1
 - 0s - loss: 0.0018 - acc: 1.0000
7 54
Epoch 1/1
 - 0s - loss: 0.0015 - acc: 1.0000
7 55
Epoch 1/1
 - 0s - loss: 0.0014 - acc: 1.0000
7 56
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
7 57
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
7 58
Epoch 1/1
 - 0s - loss: 0.0014 - acc: 1.0000
7 59
Epoch 1/1
 - 0s - loss: 0.0015 - acc: 1.0000
7 60
Epoch 1/1
 - 0s - loss: 0.0015 - acc: 1.0000
7 61
Epoch 1/1
 - 0s - loss: 0.0014 - acc: 1.0000
7 62
Epoch 1/1
 - 0s - loss: 0.0014 - acc: 1.0000
7 63
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000


8 26
Epoch 1/1
 - 0s - loss: 9.2880e-04 - acc: 1.0000
8 27
Epoch 1/1
 - 0s - loss: 9.1679e-04 - acc: 1.0000
8 28
Epoch 1/1
 - 0s - loss: 0.0012 - acc: 1.0000
8 29
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
8 30
Epoch 1/1
 - 0s - loss: 0.0012 - acc: 1.0000
8 31
Epoch 1/1
 - 0s - loss: 0.0012 - acc: 1.0000
8 32
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
8 33
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
8 34
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
8 35
Epoch 1/1
 - 0s - loss: 0.0015 - acc: 1.0000
8 36
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
8 37
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
8 38
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
8 39
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
8 40
Epoch 1/1
 - 0s - loss: 0.0016 - acc: 1.0000
8 41
Epoch 1/1
 - 0s - loss: 0.0016 - acc: 1.0000
8 42
Epoch 1/1
 - 0s - loss: 0.0015 - acc: 1.0000
8 43
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
8 44
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
8 45
Epoch 1/1
 - 0s - loss: 0.0012 - acc:

9 1
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
9 2
Epoch 1/1
 - 0s - loss: 8.7092e-04 - acc: 1.0000
9 3
Epoch 1/1
 - 0s - loss: 8.2281e-04 - acc: 1.0000
9 4
Epoch 1/1
 - 0s - loss: 7.7286e-04 - acc: 1.0000
9 5
Epoch 1/1
 - 0s - loss: 8.2509e-04 - acc: 1.0000
9 6
Epoch 1/1
 - 0s - loss: 7.3604e-04 - acc: 1.0000
9 7
Epoch 1/1
 - 0s - loss: 6.2132e-04 - acc: 1.0000
9 8
Epoch 1/1
 - 0s - loss: 5.3628e-04 - acc: 1.0000
9 9
Epoch 1/1
 - 0s - loss: 5.2150e-04 - acc: 1.0000
9 10
Epoch 1/1
 - 0s - loss: 0.0029 - acc: 1.0000
9 11
Epoch 1/1
 - 0s - loss: 0.0024 - acc: 1.0000
9 12
Epoch 1/1
 - 0s - loss: 0.0018 - acc: 1.0000
9 13
Epoch 1/1
 - 0s - loss: 0.0014 - acc: 1.0000
9 14
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
9 15
Epoch 1/1
 - 0s - loss: 9.4596e-04 - acc: 1.0000
9 16
Epoch 1/1
 - 0s - loss: 9.6990e-04 - acc: 1.0000
9 17
Epoch 1/1
 - 0s - loss: 9.3485e-04 - acc: 1.0000
9 18
Epoch 1/1
 - 0s - loss: 8.6976e-04 - acc: 1.0000
9 19
Epoch 1/1
 - 0s - loss: 8.0958e-04 - acc: 1.0000
9 20
Ep

9 153
Epoch 1/1
 - 0s - loss: 4.6656e-04 - acc: 1.0000
9 154
Epoch 1/1
 - 0s - loss: 5.0897e-04 - acc: 1.0000
9 155
Epoch 1/1
 - 0s - loss: 5.2738e-04 - acc: 1.0000
9 156
Epoch 1/1
 - 0s - loss: 4.6490e-04 - acc: 1.0000
9 157
Epoch 1/1
 - 0s - loss: 4.4876e-04 - acc: 1.0000
9 158
Epoch 1/1
 - 0s - loss: 4.1325e-04 - acc: 1.0000
9 159
Epoch 1/1
 - 0s - loss: 3.9890e-04 - acc: 1.0000
9 160
Epoch 1/1
 - 0s - loss: 4.3731e-04 - acc: 1.0000
9 161
Epoch 1/1
 - 0s - loss: 4.9305e-04 - acc: 1.0000
9 162
Epoch 1/1
 - 0s - loss: 4.6423e-04 - acc: 1.0000
9 163
Epoch 1/1
 - 0s - loss: 4.3846e-04 - acc: 1.0000
9 164
Epoch 1/1
 - 0s - loss: 3.9994e-04 - acc: 1.0000
9 165
Epoch 1/1
 - 0s - loss: 3.9427e-04 - acc: 1.0000
9 166
Epoch 1/1
 - 0s - loss: 4.7066e-04 - acc: 1.0000
9 167
Epoch 1/1
 - 0s - loss: 5.0769e-04 - acc: 1.0000
9 168
Epoch 1/1
 - 0s - loss: 5.4432e-04 - acc: 1.0000
9 169
Epoch 1/1
 - 0s - loss: 4.8737e-04 - acc: 1.0000
9 170
Epoch 1/1
 - 0s - loss: 4.3900e-04 - acc: 1.0000
9 171
Epoc

 - 0s - loss: 2.6984e-04 - acc: 1.0000
10 123
Epoch 1/1
 - 0s - loss: 2.6343e-04 - acc: 1.0000
10 124
Epoch 1/1
 - 0s - loss: 3.0062e-04 - acc: 1.0000
10 125
Epoch 1/1
 - 0s - loss: 3.0697e-04 - acc: 1.0000
10 126
Epoch 1/1
 - 0s - loss: 3.6088e-04 - acc: 1.0000
10 127
Epoch 1/1
 - 0s - loss: 3.3704e-04 - acc: 1.0000
10 128
Epoch 1/1
 - 0s - loss: 2.9936e-04 - acc: 1.0000
10 129
Epoch 1/1
 - 0s - loss: 2.9501e-04 - acc: 1.0000
10 130
Epoch 1/1
 - 0s - loss: 3.1998e-04 - acc: 1.0000
10 131
Epoch 1/1
 - 0s - loss: 3.7216e-04 - acc: 1.0000
10 132
Epoch 1/1
 - 0s - loss: 3.7518e-04 - acc: 1.0000
10 133
Epoch 1/1
 - 0s - loss: 3.4656e-04 - acc: 1.0000
10 134
Epoch 1/1
 - 0s - loss: 3.0177e-04 - acc: 1.0000
10 135
Epoch 1/1
 - 0s - loss: 2.9299e-04 - acc: 1.0000
10 136
Epoch 1/1
 - 0s - loss: 4.5138e-04 - acc: 1.0000
10 137
Epoch 1/1
 - 0s - loss: 4.5655e-04 - acc: 1.0000
10 138
Epoch 1/1
 - 0s - loss: 4.4396e-04 - acc: 1.0000
10 139
Epoch 1/1
 - 0s - loss: 4.0112e-04 - acc: 1.0000
10 140
Ep

11 91
Epoch 1/1
 - 0s - loss: 2.8344e-04 - acc: 1.0000
11 92
Epoch 1/1
 - 0s - loss: 2.4781e-04 - acc: 1.0000
11 93
Epoch 1/1
 - 0s - loss: 2.4358e-04 - acc: 1.0000
11 94
Epoch 1/1
 - 0s - loss: 2.7183e-04 - acc: 1.0000
11 95
Epoch 1/1
 - 0s - loss: 2.9990e-04 - acc: 1.0000
11 96
Epoch 1/1
 - 0s - loss: 2.7235e-04 - acc: 1.0000
11 97
Epoch 1/1
 - 0s - loss: 2.5490e-04 - acc: 1.0000
11 98
Epoch 1/1
 - 0s - loss: 2.3100e-04 - acc: 1.0000
11 99
Epoch 1/1
 - 0s - loss: 2.4172e-04 - acc: 1.0000
11 100
Epoch 1/1
 - 0s - loss: 3.1924e-04 - acc: 1.0000
11 101
Epoch 1/1
 - 0s - loss: 3.2353e-04 - acc: 1.0000
11 102
Epoch 1/1
 - 0s - loss: 3.0250e-04 - acc: 1.0000
11 103
Epoch 1/1
 - 0s - loss: 2.9346e-04 - acc: 1.0000
11 104
Epoch 1/1
 - 0s - loss: 2.5370e-04 - acc: 1.0000
11 105
Epoch 1/1
 - 0s - loss: 2.4811e-04 - acc: 1.0000
11 106
Epoch 1/1
 - 0s - loss: 2.6248e-04 - acc: 1.0000
11 107
Epoch 1/1
 - 0s - loss: 2.7844e-04 - acc: 1.0000
11 108
Epoch 1/1
 - 0s - loss: 2.8100e-04 - acc: 1.0000
1

12 59
Epoch 1/1
 - 0s - loss: 1.6820e-04 - acc: 1.0000
12 60
Epoch 1/1
 - 0s - loss: 1.6961e-04 - acc: 1.0000
12 61
Epoch 1/1
 - 0s - loss: 1.5811e-04 - acc: 1.0000
12 62
Epoch 1/1
 - 0s - loss: 1.5643e-04 - acc: 1.0000
12 63
Epoch 1/1
 - 0s - loss: 1.5311e-04 - acc: 1.0000
12 64
Epoch 1/1
 - 0s - loss: 1.5085e-04 - acc: 1.0000
12 65
Epoch 1/1
 - 0s - loss: 1.7854e-04 - acc: 1.0000
12 66
Epoch 1/1
 - 0s - loss: 1.9525e-04 - acc: 1.0000
12 67
Epoch 1/1
 - 0s - loss: 1.7267e-04 - acc: 1.0000
12 68
Epoch 1/1
 - 0s - loss: 1.5314e-04 - acc: 1.0000
12 69
Epoch 1/1
 - 0s - loss: 1.4620e-04 - acc: 1.0000
12 70
Epoch 1/1
 - 0s - loss: 2.2993e-04 - acc: 1.0000
12 71
Epoch 1/1
 - 0s - loss: 2.4859e-04 - acc: 1.0000
12 72
Epoch 1/1
 - 0s - loss: 2.3449e-04 - acc: 1.0000
12 73
Epoch 1/1
 - 0s - loss: 2.1752e-04 - acc: 1.0000
12 74
Epoch 1/1
 - 0s - loss: 2.0743e-04 - acc: 1.0000
12 75
Epoch 1/1
 - 0s - loss: 1.9917e-04 - acc: 1.0000
12 76
Epoch 1/1
 - 0s - loss: 2.1458e-04 - acc: 1.0000
12 77
Epoc

13 27
Epoch 1/1
 - 0s - loss: 1.0512e-04 - acc: 1.0000
13 28
Epoch 1/1
 - 0s - loss: 1.4019e-04 - acc: 1.0000
13 29
Epoch 1/1
 - 0s - loss: 1.5187e-04 - acc: 1.0000
13 30
Epoch 1/1
 - 0s - loss: 1.3786e-04 - acc: 1.0000
13 31
Epoch 1/1
 - 0s - loss: 1.3144e-04 - acc: 1.0000
13 32
Epoch 1/1
 - 0s - loss: 1.2322e-04 - acc: 1.0000
13 33
Epoch 1/1
 - 0s - loss: 1.2078e-04 - acc: 1.0000
13 34
Epoch 1/1
 - 0s - loss: 1.4990e-04 - acc: 1.0000
13 35
Epoch 1/1
 - 0s - loss: 1.6267e-04 - acc: 1.0000
13 36
Epoch 1/1
 - 0s - loss: 1.4792e-04 - acc: 1.0000
13 37
Epoch 1/1
 - 0s - loss: 1.3867e-04 - acc: 1.0000
13 38
Epoch 1/1
 - 0s - loss: 1.2288e-04 - acc: 1.0000
13 39
Epoch 1/1
 - 0s - loss: 1.2054e-04 - acc: 1.0000
13 40
Epoch 1/1
 - 0s - loss: 1.8438e-04 - acc: 1.0000
13 41
Epoch 1/1
 - 0s - loss: 1.8340e-04 - acc: 1.0000
13 42
Epoch 1/1
 - 0s - loss: 1.6597e-04 - acc: 1.0000
13 43
Epoch 1/1
 - 0s - loss: 1.5144e-04 - acc: 1.0000
13 44
Epoch 1/1
 - 0s - loss: 1.4283e-04 - acc: 1.0000
13 45
Epoc

13 175
Epoch 1/1
 - 0s - loss: 1.2745e-04 - acc: 1.0000
13 176
Epoch 1/1
 - 0s - loss: 1.1588e-04 - acc: 1.0000
13 177
Epoch 1/1
 - 0s - loss: 1.1203e-04 - acc: 1.0000
13 178
Epoch 1/1
 - 0s - loss: 1.4013e-04 - acc: 1.0000
13 179
Epoch 1/1
 - 0s - loss: 1.3909e-04 - acc: 1.0000
14 0
Epoch 1/1
 - 0s - loss: 2.4694e-04 - acc: 1.0000
14 1
Epoch 1/1
 - 0s - loss: 1.4166e-04 - acc: 1.0000
14 2
Epoch 1/1
 - 0s - loss: 1.0890e-04 - acc: 1.0000
14 3
Epoch 1/1
 - 0s - loss: 1.0371e-04 - acc: 1.0000
14 4
Epoch 1/1
 - 0s - loss: 9.8011e-05 - acc: 1.0000
14 5
Epoch 1/1
 - 0s - loss: 1.0282e-04 - acc: 1.0000
14 6
Epoch 1/1
 - 0s - loss: 9.1452e-05 - acc: 1.0000
14 7
Epoch 1/1
 - 0s - loss: 7.6588e-05 - acc: 1.0000
14 8
Epoch 1/1
 - 0s - loss: 6.6723e-05 - acc: 1.0000
14 9
Epoch 1/1
 - 0s - loss: 6.5095e-05 - acc: 1.0000
14 10
Epoch 1/1
 - 0s - loss: 3.6343e-04 - acc: 1.0000
14 11
Epoch 1/1
 - 0s - loss: 2.9661e-04 - acc: 1.0000
14 12
Epoch 1/1
 - 0s - loss: 2.2318e-04 - acc: 1.0000
14 13
Epoch 1/1

 - 0s - loss: 7.6331e-05 - acc: 1.0000
14 144
Epoch 1/1
 - 0s - loss: 7.2017e-05 - acc: 1.0000
14 145
Epoch 1/1
 - 0s - loss: 6.8140e-05 - acc: 1.0000
14 146
Epoch 1/1
 - 0s - loss: 6.2119e-05 - acc: 1.0000
14 147
Epoch 1/1
 - 0s - loss: 6.0954e-05 - acc: 1.0000
14 148
Epoch 1/1
 - 0s - loss: 7.2250e-05 - acc: 1.0000
14 149
Epoch 1/1
 - 0s - loss: 7.6819e-05 - acc: 1.0000
14 150
Epoch 1/1
 - 0s - loss: 7.2869e-05 - acc: 1.0000
14 151
Epoch 1/1
 - 0s - loss: 6.6285e-05 - acc: 1.0000
14 152
Epoch 1/1
 - 0s - loss: 5.9526e-05 - acc: 1.0000
14 153
Epoch 1/1
 - 0s - loss: 5.8038e-05 - acc: 1.0000
14 154
Epoch 1/1
 - 0s - loss: 6.3468e-05 - acc: 1.0000
14 155
Epoch 1/1
 - 0s - loss: 6.5468e-05 - acc: 1.0000
14 156
Epoch 1/1
 - 0s - loss: 5.6970e-05 - acc: 1.0000
14 157
Epoch 1/1
 - 0s - loss: 5.6002e-05 - acc: 1.0000
14 158
Epoch 1/1
 - 0s - loss: 5.1522e-05 - acc: 1.0000
14 159
Epoch 1/1
 - 0s - loss: 4.9472e-05 - acc: 1.0000
14 160
Epoch 1/1
 - 0s - loss: 5.4318e-05 - acc: 1.0000
14 161
Ep

15 112
Epoch 1/1
 - 0s - loss: 4.7141e-05 - acc: 1.0000
15 113
Epoch 1/1
 - 0s - loss: 5.0363e-05 - acc: 1.0000
15 114
Epoch 1/1
 - 0s - loss: 5.2768e-05 - acc: 1.0000
15 115
Epoch 1/1
 - 0s - loss: 4.6202e-05 - acc: 1.0000
15 116
Epoch 1/1
 - 0s - loss: 4.3785e-05 - acc: 1.0000
15 117
Epoch 1/1
 - 0s - loss: 4.2849e-05 - acc: 1.0000
15 118
Epoch 1/1
 - 0s - loss: 4.4604e-05 - acc: 1.0000
15 119
Epoch 1/1
 - 0s - loss: 4.4604e-05 - acc: 1.0000
15 120
Epoch 1/1
 - 0s - loss: 3.9463e-05 - acc: 1.0000
15 121
Epoch 1/1
 - 0s - loss: 3.6846e-05 - acc: 1.0000
15 122
Epoch 1/1
 - 0s - loss: 3.3523e-05 - acc: 1.0000
15 123
Epoch 1/1
 - 0s - loss: 3.2924e-05 - acc: 1.0000
15 124
Epoch 1/1
 - 0s - loss: 3.7958e-05 - acc: 1.0000
15 125
Epoch 1/1
 - 0s - loss: 3.8876e-05 - acc: 1.0000
15 126
Epoch 1/1
 - 0s - loss: 4.5212e-05 - acc: 1.0000
15 127
Epoch 1/1
 - 0s - loss: 4.2044e-05 - acc: 1.0000
15 128
Epoch 1/1
 - 0s - loss: 3.7427e-05 - acc: 1.0000
15 129
Epoch 1/1
 - 0s - loss: 3.6971e-05 - acc:

16 80
Epoch 1/1
 - 0s - loss: 3.3106e-05 - acc: 1.0000
16 81
Epoch 1/1
 - 0s - loss: 3.1738e-05 - acc: 1.0000
16 82
Epoch 1/1
 - 0s - loss: 3.6048e-05 - acc: 1.0000
16 83
Epoch 1/1
 - 0s - loss: 3.6143e-05 - acc: 1.0000
16 84
Epoch 1/1
 - 0s - loss: 4.3096e-05 - acc: 1.0000
16 85
Epoch 1/1
 - 0s - loss: 3.9025e-05 - acc: 1.0000
16 86
Epoch 1/1
 - 0s - loss: 3.6516e-05 - acc: 1.0000
16 87
Epoch 1/1
 - 0s - loss: 3.6036e-05 - acc: 1.0000
16 88
Epoch 1/1
 - 0s - loss: 4.0342e-05 - acc: 1.0000
16 89
Epoch 1/1
 - 0s - loss: 4.4798e-05 - acc: 1.0000
16 90
Epoch 1/1
 - 0s - loss: 4.0208e-05 - acc: 1.0000
16 91
Epoch 1/1
 - 0s - loss: 3.6497e-05 - acc: 1.0000
16 92
Epoch 1/1
 - 0s - loss: 3.1830e-05 - acc: 1.0000
16 93
Epoch 1/1
 - 0s - loss: 3.1398e-05 - acc: 1.0000
16 94
Epoch 1/1
 - 0s - loss: 3.5147e-05 - acc: 1.0000
16 95
Epoch 1/1
 - 0s - loss: 3.8876e-05 - acc: 1.0000
16 96
Epoch 1/1
 - 0s - loss: 3.5240e-05 - acc: 1.0000
16 97
Epoch 1/1
 - 0s - loss: 3.2885e-05 - acc: 1.0000
16 98
Epoc

17 48
Epoch 1/1
 - 0s - loss: 2.9336e-05 - acc: 1.0000
17 49
Epoch 1/1
 - 0s - loss: 2.7282e-05 - acc: 1.0000
17 50
Epoch 1/1
 - 0s - loss: 2.4451e-05 - acc: 1.0000
17 51
Epoch 1/1
 - 0s - loss: 2.3613e-05 - acc: 1.0000
17 52
Epoch 1/1
 - 0s - loss: 2.8018e-05 - acc: 1.0000
17 53
Epoch 1/1
 - 0s - loss: 2.8367e-05 - acc: 1.0000
17 54
Epoch 1/1
 - 0s - loss: 2.3074e-05 - acc: 1.0000
17 55
Epoch 1/1
 - 0s - loss: 2.1113e-05 - acc: 1.0000
17 56
Epoch 1/1
 - 0s - loss: 2.0537e-05 - acc: 1.0000
17 57
Epoch 1/1
 - 0s - loss: 2.0487e-05 - acc: 1.0000
17 58
Epoch 1/1
 - 0s - loss: 2.2928e-05 - acc: 1.0000
17 59
Epoch 1/1
 - 0s - loss: 2.3184e-05 - acc: 1.0000
17 60
Epoch 1/1
 - 0s - loss: 2.3285e-05 - acc: 1.0000
17 61
Epoch 1/1
 - 0s - loss: 2.1732e-05 - acc: 1.0000
17 62
Epoch 1/1
 - 0s - loss: 2.1461e-05 - acc: 1.0000
17 63
Epoch 1/1
 - 0s - loss: 2.0996e-05 - acc: 1.0000
17 64
Epoch 1/1
 - 0s - loss: 2.0663e-05 - acc: 1.0000
17 65
Epoch 1/1
 - 0s - loss: 2.4436e-05 - acc: 1.0000
17 66
Epoc

18 16
Epoch 1/1
 - 0s - loss: 2.5331e-05 - acc: 1.0000
18 17
Epoch 1/1
 - 0s - loss: 2.4237e-05 - acc: 1.0000
18 18
Epoch 1/1
 - 0s - loss: 2.0961e-05 - acc: 1.0000
18 19
Epoch 1/1
 - 0s - loss: 1.9420e-05 - acc: 1.0000
18 20
Epoch 1/1
 - 0s - loss: 1.8192e-05 - acc: 1.0000
18 21
Epoch 1/1
 - 0s - loss: 1.7155e-05 - acc: 1.0000
18 22
Epoch 1/1
 - 0s - loss: 1.8421e-05 - acc: 1.0000
18 23
Epoch 1/1
 - 0s - loss: 1.7918e-05 - acc: 1.0000
18 24
Epoch 1/1
 - 0s - loss: 1.7050e-05 - acc: 1.0000
18 25
Epoch 1/1
 - 0s - loss: 1.5116e-05 - acc: 1.0000
18 26
Epoch 1/1
 - 0s - loss: 1.4362e-05 - acc: 1.0000
18 27
Epoch 1/1
 - 0s - loss: 1.4037e-05 - acc: 1.0000
18 28
Epoch 1/1
 - 0s - loss: 1.9345e-05 - acc: 1.0000
18 29
Epoch 1/1
 - 0s - loss: 2.0809e-05 - acc: 1.0000
18 30
Epoch 1/1
 - 0s - loss: 1.8624e-05 - acc: 1.0000
18 31
Epoch 1/1
 - 0s - loss: 1.7751e-05 - acc: 1.0000
18 32
Epoch 1/1
 - 0s - loss: 1.6651e-05 - acc: 1.0000
18 33
Epoch 1/1
 - 0s - loss: 1.6335e-05 - acc: 1.0000
18 34
Epoc

18 164
Epoch 1/1
 - 0s - loss: 1.0076e-05 - acc: 1.0000
18 165
Epoch 1/1
 - 0s - loss: 9.9600e-06 - acc: 1.0000
18 166
Epoch 1/1
 - 0s - loss: 1.2049e-05 - acc: 1.0000
18 167
Epoch 1/1
 - 0s - loss: 1.3074e-05 - acc: 1.0000
18 168
Epoch 1/1
 - 0s - loss: 1.3563e-05 - acc: 1.0000
18 169
Epoch 1/1
 - 0s - loss: 1.2118e-05 - acc: 1.0000
18 170
Epoch 1/1
 - 0s - loss: 1.0994e-05 - acc: 1.0000
18 171
Epoch 1/1
 - 0s - loss: 1.1006e-05 - acc: 1.0000
18 172
Epoch 1/1
 - 0s - loss: 1.3960e-05 - acc: 1.0000
18 173
Epoch 1/1
 - 0s - loss: 1.6240e-05 - acc: 1.0000
18 174
Epoch 1/1
 - 0s - loss: 1.8233e-05 - acc: 1.0000
18 175
Epoch 1/1
 - 0s - loss: 1.7140e-05 - acc: 1.0000
18 176
Epoch 1/1
 - 0s - loss: 1.5581e-05 - acc: 1.0000
18 177
Epoch 1/1
 - 0s - loss: 1.5056e-05 - acc: 1.0000
18 178
Epoch 1/1
 - 0s - loss: 1.9038e-05 - acc: 1.0000
18 179
Epoch 1/1
 - 0s - loss: 1.8853e-05 - acc: 1.0000
19 0
Epoch 1/1
 - 0s - loss: 3.6803e-05 - acc: 1.0000
19 1
Epoch 1/1
 - 0s - loss: 2.0487e-05 - acc: 1.0

KeyboardInterrupt: 

In [44]:
# evaluate model on new data
X_e, y_e = generate(1)
yhat = model.predict(X_e, batch_size=5)
print('Expected:  %s' % one_hot_decode(y_e))
print('Predicted: %s' % one_hot_decode(yhat))

Expected:  [2, 1, 1, 1, 2, 8, 7, 1, 1, 1, 2, 1, 9, 1, 1, 1, 7, 1, 1, 1]
Predicted: [2, 1, 1, 1, 2, 8, 7, 1, 1, 1, 2, 1, 9, 1, 1, 1, 7, 1, 1, 1]
