In [1]:
# example making new class predictions for a classification problem
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from random import randint
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from keras.utils import np_utils

Using TensorFlow backend.
/home/greed/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/greed/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/greed/anaconda3/envs/tensorflow_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])

In [2]:
# https://machinelearningmastery.com/how-to-make-classification-and-regression-predictions-for-deep-learning-models-in-keras/
# example making new class predictions for a classification problem
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import MinMaxScaler

def work():
    # generate 2d classification dataset
    X, y = make_blobs(n_samples=100, centers=2, n_features=2, random_state=1)
    scalar = MinMaxScaler()
    scalar.fit(X)
    X = scalar.transform(X)
    # define and fit the final model
    model = Sequential()
    model.add(Dense(4, input_dim=2, activation='relu'))
    model.add(Dense(4, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    model.fit(X, y, epochs=500, verbose=0)
    # new instances where we do not know the answer
    Xnew, _ = make_blobs(n_samples=3, centers=2, n_features=2, random_state=1)
    Xnew = scalar.transform(Xnew)
    # make a prediction
    ynew = model.predict_classes(Xnew)
    # show the inputs and predicted outputs
    for i in range(len(Xnew)):
        print("X=%s, Predicted=%s" % (Xnew[i], ynew[i]))

In [47]:
print(X[0:5])
print('-'*20)
print(y[0:5])

[[9 2 6 0]
 [2 6 3 1]
 [6 3 8 2]
 [3 8 5 3]
 [8 5 4 4]]
--------------------
[[0]
 [1]
 [2]
 [3]
 [4]]


In [77]:
def generate_main_seq():
    rand_nums=[randint(0, 9) for _ in range(25*700)]
    return rand_nums

seq=3
max_len=40
f = generate_main_seq()

x=[]
for i in range(seq, max_len):
    #print(f[rec:rec+seq])
    X_cur = f[ i : i+seq ]
    d = { 'x': X_cur }
    a = X_cur
    if d not in x: 
        x.append(a)
    else:
        print('double')
        
df=pd.DataFrame(x)
df['y']=[i for i in range(0,len(df))]
y=df['y']
y = np.array(df['y']).reshape(len(df),1)
print('y shape:', y.shape, '|||', 'x shape:', np.array(df.values).shape)
print('y', len(np.array(y)))

X=np.array(df.values)
y[:10]

y shape: (37, 1) ||| x shape: (37, 4)
y 37


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [142]:
def generate():
    seq=0
    max_len=190
    q=0
    x=[]
    y=[]
    for i in range(seq, max_len):
        r = randint(0, 9)
        if i%50==0: q+=1
        if q>=10: q=0
        rnd_line = [randint(0, 9) for _ in range(3)]
        rnd_line = np.append(q, rnd_line)
        rnd_line = np.append(q, rnd_line)
        rnd_line = np.append(q, rnd_line)
        x.append(rnd_line)
        #print(rnd_line)
        y.append(q)
    x = pd.DataFrame(x).values
    return x, y
X, y = generate()

In [143]:
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
dummy_y = np_utils.to_categorical(encoded_Y)


In [144]:
print('encoded: len', len(encoded_Y), '\n', encoded_Y[:3])
print('dummy:', dummy_y.shape, '\n', dummy_y[:10])
print('X: len', len(X), 'shape:', X.shape, '\n', X[:10])


encoded: len 190 
 [0 0 0]
dummy: (190, 4) 
 [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
X: len 190 shape: (190, 6) 
 [[1 1 1 6 1 6]
 [1 1 1 5 0 1]
 [1 1 1 8 4 3]
 [1 1 1 2 0 2]
 [1 1 1 1 1 4]
 [1 1 1 6 9 8]
 [1 1 1 2 1 9]
 [1 1 1 4 2 1]
 [1 1 1 2 8 2]
 [1 1 1 3 9 5]]


In [148]:
#https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(8, input_dim=6, activation='relu'))
	model.add(Dense(4, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

estimator = KerasClassifier(build_fn=baseline_model, epochs=500, batch_size=5, verbose=1)

kfold = KFold(n_splits=10, shuffle=True)
#results = cross_val_score(estimator, X, dummy_y, cv=kfold)
estimator.fit(X, dummy_y)

#estimator = KerasClassifier(build_fn=SS.create_model, nb_epoch=10, verbose=0)
#estimator = KerasClassifier(build_fn=model, epochs=200, batch_size=5, verbose=1)
#kfold = KFold(n_splits=10, shuffle=True)
#
#results = cross_val_score(estimator, X, dummy_y, cv=kfold)

print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Epoch 1/500
190/190 [==============================] - 4s 22ms/step - loss: 2.8005 - acc: 0.2368
Epoch 2/500
190/190 [==============================] - 0s 548us/step - loss: 2.1762 - acc: 0.2158
Epoch 3/500
190/190 [==============================] - 0s 545us/step - loss: 1.8146 - acc: 0.2421
Epoch 4/500
190/190 [==============================] - 0s 541us/step - loss: 1.6254 - acc: 0.2789
Epoch 5/500
190/190 [==============================] - 0s 542us/step - loss: 1.5320 - acc: 0.3053
Epoch 6/500
190/190 [==============================] - 0s 537us/step - loss: 1.4756 - acc: 0.3105
Epoch 7/500
190/190 [==============================] - 0s 546us/step - loss: 1.4383 - acc: 0.3053
Epoch 8/500
190/190 [==============================] - 0s 540us/step - loss: 1.4090 - acc: 0.3158
Epoch 9/500
190/190 [==============================] - 0s 539us/step - loss: 1.3909 - acc: 0.3263
Epoch 10/500
190/190 [==============================] - 0s 538us/step - loss: 1.3764 - acc: 0.3737
Epoch 11/500
190/190

190/190 [==============================] - 0s 537us/step - loss: 0.4619 - acc: 0.8579
Epoch 84/500
190/190 [==============================] - 0s 537us/step - loss: 0.4585 - acc: 0.8684
Epoch 85/500
190/190 [==============================] - 0s 534us/step - loss: 0.4513 - acc: 0.8684
Epoch 86/500
190/190 [==============================] - 0s 536us/step - loss: 0.4487 - acc: 0.8684
Epoch 87/500
190/190 [==============================] - 0s 540us/step - loss: 0.4426 - acc: 0.8842
Epoch 88/500
190/190 [==============================] - 0s 540us/step - loss: 0.4346 - acc: 0.8895
Epoch 89/500
190/190 [==============================] - 0s 540us/step - loss: 0.4324 - acc: 0.8842
Epoch 90/500
190/190 [==============================] - 0s 544us/step - loss: 0.4254 - acc: 0.9000
Epoch 91/500
190/190 [==============================] - 0s 540us/step - loss: 0.4226 - acc: 0.8947
Epoch 92/500
190/190 [==============================] - 0s 539us/step - loss: 0.4166 - acc: 0.8947
Epoch 93/500
190/190 [=

190/190 [==============================] - 0s 539us/step - loss: 0.1748 - acc: 0.9737
Epoch 166/500
190/190 [==============================] - 0s 546us/step - loss: 0.1734 - acc: 0.9632
Epoch 167/500
190/190 [==============================] - 0s 542us/step - loss: 0.1696 - acc: 0.9789
Epoch 168/500
190/190 [==============================] - 0s 537us/step - loss: 0.1692 - acc: 0.9684
Epoch 169/500
190/190 [==============================] - 0s 537us/step - loss: 0.1657 - acc: 0.9842
Epoch 170/500
190/190 [==============================] - 0s 544us/step - loss: 0.1627 - acc: 0.9789
Epoch 171/500
190/190 [==============================] - 0s 539us/step - loss: 0.1597 - acc: 0.9789
Epoch 172/500
190/190 [==============================] - 0s 533us/step - loss: 0.1586 - acc: 0.9842
Epoch 173/500
190/190 [==============================] - 0s 537us/step - loss: 0.1556 - acc: 0.9789
Epoch 174/500
190/190 [==============================] - 0s 539us/step - loss: 0.1534 - acc: 0.9789
Epoch 175/500


190/190 [==============================] - 0s 532us/step - loss: 0.0605 - acc: 0.9895
Epoch 248/500
190/190 [==============================] - 0s 536us/step - loss: 0.0618 - acc: 0.9895
Epoch 249/500
190/190 [==============================] - 0s 531us/step - loss: 0.0585 - acc: 0.9895
Epoch 250/500
190/190 [==============================] - 0s 536us/step - loss: 0.0570 - acc: 1.0000
Epoch 251/500
190/190 [==============================] - 0s 542us/step - loss: 0.0559 - acc: 0.9947
Epoch 252/500
190/190 [==============================] - 0s 540us/step - loss: 0.0581 - acc: 0.9947
Epoch 253/500
190/190 [==============================] - 0s 542us/step - loss: 0.0565 - acc: 1.0000
Epoch 254/500
190/190 [==============================] - 0s 534us/step - loss: 0.0541 - acc: 0.9895
Epoch 255/500
190/190 [==============================] - 0s 538us/step - loss: 0.0523 - acc: 1.0000
Epoch 256/500
190/190 [==============================] - 0s 539us/step - loss: 0.0518 - acc: 1.0000
Epoch 257/500


190/190 [==============================] - 0s 540us/step - loss: 0.0172 - acc: 1.0000
Epoch 330/500
190/190 [==============================] - 0s 539us/step - loss: 0.0173 - acc: 1.0000
Epoch 331/500
190/190 [==============================] - 0s 539us/step - loss: 0.0169 - acc: 1.0000
Epoch 332/500
190/190 [==============================] - 0s 541us/step - loss: 0.0168 - acc: 1.0000
Epoch 333/500
190/190 [==============================] - 0s 540us/step - loss: 0.0161 - acc: 1.0000
Epoch 334/500
190/190 [==============================] - 0s 535us/step - loss: 0.0159 - acc: 1.0000
Epoch 335/500
190/190 [==============================] - 0s 536us/step - loss: 0.0157 - acc: 1.0000
Epoch 336/500
190/190 [==============================] - 0s 539us/step - loss: 0.0156 - acc: 1.0000
Epoch 337/500
190/190 [==============================] - 0s 531us/step - loss: 0.0156 - acc: 1.0000
Epoch 338/500
190/190 [==============================] - 0s 537us/step - loss: 0.0158 - acc: 1.0000
Epoch 339/500


190/190 [==============================] - 0s 537us/step - loss: 0.0048 - acc: 1.0000
Epoch 412/500
190/190 [==============================] - 0s 540us/step - loss: 0.0049 - acc: 1.0000
Epoch 413/500
190/190 [==============================] - 0s 534us/step - loss: 0.0047 - acc: 1.0000
Epoch 414/500
190/190 [==============================] - 0s 531us/step - loss: 0.0046 - acc: 1.0000
Epoch 415/500
190/190 [==============================] - 0s 541us/step - loss: 0.0045 - acc: 1.0000
Epoch 416/500
190/190 [==============================] - 0s 539us/step - loss: 0.0045 - acc: 1.0000
Epoch 417/500
190/190 [==============================] - 0s 539us/step - loss: 0.0044 - acc: 1.0000
Epoch 418/500
190/190 [==============================] - 0s 535us/step - loss: 0.0042 - acc: 1.0000
Epoch 419/500
190/190 [==============================] - 0s 538us/step - loss: 0.0042 - acc: 1.0000
Epoch 420/500
190/190 [==============================] - 0s 536us/step - loss: 0.0043 - acc: 1.0000
Epoch 421/500


190/190 [==============================] - 0s 543us/step - loss: 0.0013 - acc: 1.0000
Epoch 494/500
190/190 [==============================] - 0s 544us/step - loss: 0.0013 - acc: 1.0000
Epoch 495/500
190/190 [==============================] - 0s 538us/step - loss: 0.0012 - acc: 1.0000
Epoch 496/500
190/190 [==============================] - 0s 534us/step - loss: 0.0012 - acc: 1.0000
Epoch 497/500
190/190 [==============================] - 0s 543us/step - loss: 0.0012 - acc: 1.0000
Epoch 498/500
190/190 [==============================] - 0s 533us/step - loss: 0.0012 - acc: 1.0000
Epoch 499/500
190/190 [==============================] - 0s 544us/step - loss: 0.0012 - acc: 1.0000
Epoch 500/500
190/190 [==============================] - 0s 545us/step - loss: 0.0012 - acc: 1.0000
Baseline: 99.47% (1.58%)


In [221]:
import inspect

print(inspect.getfullargspec(estimator.fit))

X_test=np.array([3, 3, 3, 8, 1, 7]).reshape(1,6)
print('test:', X_test)

print(y_pred)
y_pred = estimator.predict( [X_test] )
print(y_pred)

FullArgSpec(args=['self', 'x', 'y', 'sample_weight'], varargs=None, varkw='kwargs', defaults=(None,), kwonlyargs=[], kwonlydefaults=None, annotations={})
test: [[3 3 3 8 1 7]]
[1]
1/1 [==============================] - 0s 6ms/step
[2]


In [99]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
# load dataset
dataframe = pandas.read_csv("iris.data", header=None)
dataset = dataframe.values
X = dataset[:,0:4].astype(float)
Y = dataset[:,4]
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
 
# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(8, input_dim=4, activation='relu'))
	model.add(Dense(3, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model
 
print(X[:3])
print(dummy_y[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [100]:
print('encoded: len', len(encoded_Y), '\n', encoded_Y[:3])
print('dummy:', dummy_y.shape, '\n', dummy_y[:3])
print('X: len', len(X), 'shape:', X.shape, '\n', X[:3])

encoded: len 150 
 [0 0 0]
dummy: (150, 3) 
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
X: len 150 shape: (150, 4) 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [101]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=1)
kfold = KFold(n_splits=10, shuffle=True)
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Epoch 1/200
135/135 [==============================] - 3s 23ms/step - loss: 1.0040 - acc: 0.6444
Epoch 2/200
135/135 [==============================] - 0s 502us/step - loss: 0.8857 - acc: 0.6519
Epoch 3/200
135/135 [==============================] - 0s 519us/step - loss: 0.8031 - acc: 0.6519
Epoch 4/200
135/135 [==============================] - 0s 505us/step - loss: 0.7425 - acc: 0.6593
Epoch 5/200
135/135 [==============================] - 0s 505us/step - loss: 0.7062 - acc: 0.6593
Epoch 6/200
135/135 [==============================] - 0s 508us/step - loss: 0.6765 - acc: 0.6667
Epoch 7/200
135/135 [==============================] - 0s 511us/step - loss: 0.6474 - acc: 0.6667
Epoch 8/200
135/135 [==============================] - 0s 521us/step - loss: 0.6192 - acc: 0.6667
Epoch 9/200
135/135 [==============================] - 0s 505us/step - loss: 0.5923 - acc: 0.6667
Epoch 10/200
135/135 [==============================] - 0s 511us/step - loss: 0.5660 - acc: 0.6741
Epoch 11/200
135/135

135/135 [==============================] - 0s 510us/step - loss: 0.1778 - acc: 0.9556
Epoch 84/200
135/135 [==============================] - 0s 506us/step - loss: 0.1742 - acc: 0.9630
Epoch 85/200
135/135 [==============================] - 0s 509us/step - loss: 0.1725 - acc: 0.9630
Epoch 86/200
135/135 [==============================] - 0s 508us/step - loss: 0.1707 - acc: 0.9630
Epoch 87/200
135/135 [==============================] - 0s 504us/step - loss: 0.1699 - acc: 0.9630
Epoch 88/200
135/135 [==============================] - 0s 509us/step - loss: 0.1698 - acc: 0.9630
Epoch 89/200
135/135 [==============================] - 0s 517us/step - loss: 0.1679 - acc: 0.9630
Epoch 90/200
135/135 [==============================] - 0s 510us/step - loss: 0.1651 - acc: 0.9630
Epoch 91/200
135/135 [==============================] - 0s 513us/step - loss: 0.1636 - acc: 0.9630
Epoch 92/200
135/135 [==============================] - 0s 506us/step - loss: 0.1635 - acc: 0.9630
Epoch 93/200
135/135 [=

135/135 [==============================] - 0s 507us/step - loss: 0.1045 - acc: 0.9704
Epoch 166/200
135/135 [==============================] - 0s 518us/step - loss: 0.1050 - acc: 0.9704
Epoch 167/200
135/135 [==============================] - 0s 509us/step - loss: 0.1040 - acc: 0.9704
Epoch 168/200
135/135 [==============================] - 0s 512us/step - loss: 0.1036 - acc: 0.9704
Epoch 169/200
135/135 [==============================] - 0s 518us/step - loss: 0.1086 - acc: 0.9704
Epoch 170/200
135/135 [==============================] - 0s 517us/step - loss: 0.1056 - acc: 0.9556
Epoch 171/200
135/135 [==============================] - 0s 513us/step - loss: 0.1030 - acc: 0.9630
Epoch 172/200
135/135 [==============================] - 0s 512us/step - loss: 0.1043 - acc: 0.9704
Epoch 173/200
135/135 [==============================] - 0s 508us/step - loss: 0.1007 - acc: 0.9704
Epoch 174/200
135/135 [==============================] - 0s 519us/step - loss: 0.1015 - acc: 0.9704
Epoch 175/200


135/135 [==============================] - 0s 515us/step - loss: 0.3133 - acc: 0.9704
Epoch 48/200
135/135 [==============================] - 0s 512us/step - loss: 0.3103 - acc: 0.9630
Epoch 49/200
135/135 [==============================] - 0s 509us/step - loss: 0.3061 - acc: 0.9852
Epoch 50/200
135/135 [==============================] - 0s 520us/step - loss: 0.2975 - acc: 0.9556
Epoch 51/200
135/135 [==============================] - 0s 513us/step - loss: 0.2910 - acc: 0.9704
Epoch 52/200
135/135 [==============================] - 0s 516us/step - loss: 0.2867 - acc: 0.9704
Epoch 53/200
135/135 [==============================] - 0s 517us/step - loss: 0.2805 - acc: 0.9630
Epoch 54/200
135/135 [==============================] - 0s 520us/step - loss: 0.2754 - acc: 0.9778
Epoch 55/200
135/135 [==============================] - 0s 514us/step - loss: 0.2712 - acc: 0.9704
Epoch 56/200
135/135 [==============================] - 0s 514us/step - loss: 0.2677 - acc: 0.9778
Epoch 57/200
135/135 [=

135/135 [==============================] - 0s 519us/step - loss: 0.1152 - acc: 0.9778
Epoch 130/200
135/135 [==============================] - 0s 516us/step - loss: 0.1153 - acc: 0.9778
Epoch 131/200
135/135 [==============================] - 0s 522us/step - loss: 0.1146 - acc: 0.9778
Epoch 132/200
135/135 [==============================] - 0s 519us/step - loss: 0.1145 - acc: 0.9778
Epoch 133/200
135/135 [==============================] - 0s 515us/step - loss: 0.1121 - acc: 0.9778
Epoch 134/200
135/135 [==============================] - 0s 514us/step - loss: 0.1111 - acc: 0.9778
Epoch 135/200
135/135 [==============================] - 0s 521us/step - loss: 0.1104 - acc: 0.9778
Epoch 136/200
135/135 [==============================] - 0s 509us/step - loss: 0.1094 - acc: 0.9778
Epoch 137/200
135/135 [==============================] - 0s 511us/step - loss: 0.1085 - acc: 0.9778
Epoch 138/200
135/135 [==============================] - 0s 523us/step - loss: 0.1091 - acc: 0.9778
Epoch 139/200


135/135 [==============================] - 0s 517us/step - loss: 1.0097 - acc: 0.3556
Epoch 11/200
135/135 [==============================] - 0s 522us/step - loss: 0.9617 - acc: 0.3556
Epoch 12/200
135/135 [==============================] - 0s 522us/step - loss: 0.9109 - acc: 0.4593
Epoch 13/200
135/135 [==============================] - 0s 516us/step - loss: 0.8689 - acc: 0.5926
Epoch 14/200
135/135 [==============================] - 0s 522us/step - loss: 0.8271 - acc: 0.7111
Epoch 15/200
135/135 [==============================] - 0s 520us/step - loss: 0.7908 - acc: 0.7407
Epoch 16/200
135/135 [==============================] - 0s 524us/step - loss: 0.7577 - acc: 0.7185
Epoch 17/200
135/135 [==============================] - 0s 519us/step - loss: 0.7281 - acc: 0.7704
Epoch 18/200
135/135 [==============================] - 0s 526us/step - loss: 0.6987 - acc: 0.7556
Epoch 19/200
135/135 [==============================] - 0s 522us/step - loss: 0.6753 - acc: 0.8074
Epoch 20/200
135/135 [=

135/135 [==============================] - 0s 514us/step - loss: 0.2321 - acc: 0.9704
Epoch 93/200
135/135 [==============================] - 0s 531us/step - loss: 0.2285 - acc: 0.9778
Epoch 94/200
135/135 [==============================] - 0s 524us/step - loss: 0.2260 - acc: 0.9704
Epoch 95/200
135/135 [==============================] - 0s 516us/step - loss: 0.2233 - acc: 0.9778
Epoch 96/200
135/135 [==============================] - 0s 513us/step - loss: 0.2210 - acc: 0.9778
Epoch 97/200
135/135 [==============================] - 0s 531us/step - loss: 0.2184 - acc: 0.9778
Epoch 98/200
135/135 [==============================] - 0s 520us/step - loss: 0.2156 - acc: 0.9778
Epoch 99/200
135/135 [==============================] - 0s 518us/step - loss: 0.2131 - acc: 0.9778
Epoch 100/200
135/135 [==============================] - 0s 532us/step - loss: 0.2111 - acc: 0.9704
Epoch 101/200
135/135 [==============================] - 0s 539us/step - loss: 0.2104 - acc: 0.9704
Epoch 102/200
135/135

135/135 [==============================] - 0s 532us/step - loss: 0.1107 - acc: 0.9852
Epoch 175/200
135/135 [==============================] - 0s 519us/step - loss: 0.1126 - acc: 0.9704
Epoch 176/200
135/135 [==============================] - 0s 515us/step - loss: 0.1110 - acc: 0.9852
Epoch 177/200
135/135 [==============================] - 0s 522us/step - loss: 0.1079 - acc: 0.9852
Epoch 178/200
135/135 [==============================] - 0s 514us/step - loss: 0.1077 - acc: 0.9852
Epoch 179/200
135/135 [==============================] - 0s 513us/step - loss: 0.1075 - acc: 0.9852
Epoch 180/200
135/135 [==============================] - 0s 514us/step - loss: 0.1078 - acc: 0.9852
Epoch 181/200
135/135 [==============================] - 0s 511us/step - loss: 0.1077 - acc: 0.9704
Epoch 182/200
135/135 [==============================] - 0s 515us/step - loss: 0.1066 - acc: 0.9852
Epoch 183/200
135/135 [==============================] - 0s 517us/step - loss: 0.1050 - acc: 0.9852
Epoch 184/200


135/135 [==============================] - 0s 522us/step - loss: 0.2783 - acc: 0.9556
Epoch 57/200
135/135 [==============================] - 0s 522us/step - loss: 0.2754 - acc: 0.9630
Epoch 58/200
135/135 [==============================] - 0s 528us/step - loss: 0.2695 - acc: 0.9630
Epoch 59/200
135/135 [==============================] - 0s 518us/step - loss: 0.2643 - acc: 0.9556
Epoch 60/200
135/135 [==============================] - 0s 515us/step - loss: 0.2606 - acc: 0.9630
Epoch 61/200
135/135 [==============================] - 0s 524us/step - loss: 0.2541 - acc: 0.9704
Epoch 62/200
135/135 [==============================] - 0s 520us/step - loss: 0.2509 - acc: 0.9630
Epoch 63/200
135/135 [==============================] - 0s 524us/step - loss: 0.2460 - acc: 0.9630
Epoch 64/200
135/135 [==============================] - 0s 534us/step - loss: 0.2427 - acc: 0.9630
Epoch 65/200
135/135 [==============================] - 0s 528us/step - loss: 0.2388 - acc: 0.9630
Epoch 66/200
135/135 [=

135/135 [==============================] - 0s 514us/step - loss: 0.1146 - acc: 0.9778
Epoch 139/200
135/135 [==============================] - 0s 519us/step - loss: 0.1164 - acc: 0.9704
Epoch 140/200
135/135 [==============================] - 0s 516us/step - loss: 0.1136 - acc: 0.9704
Epoch 141/200
135/135 [==============================] - 0s 523us/step - loss: 0.1136 - acc: 0.9778
Epoch 142/200
135/135 [==============================] - 0s 526us/step - loss: 0.1127 - acc: 0.9778
Epoch 143/200
135/135 [==============================] - 0s 519us/step - loss: 0.1119 - acc: 0.9778
Epoch 144/200
135/135 [==============================] - 0s 525us/step - loss: 0.1108 - acc: 0.9778
Epoch 145/200
135/135 [==============================] - 0s 517us/step - loss: 0.1097 - acc: 0.9778
Epoch 146/200
135/135 [==============================] - 0s 529us/step - loss: 0.1099 - acc: 0.9778
Epoch 147/200
135/135 [==============================] - 0s 519us/step - loss: 0.1097 - acc: 0.9778
Epoch 148/200


135/135 [==============================] - 0s 524us/step - loss: 0.5252 - acc: 0.8444
Epoch 20/200
135/135 [==============================] - 0s 516us/step - loss: 0.5143 - acc: 0.8444
Epoch 21/200
135/135 [==============================] - 0s 527us/step - loss: 0.5046 - acc: 0.8444
Epoch 22/200
135/135 [==============================] - 0s 514us/step - loss: 0.4949 - acc: 0.8519
Epoch 23/200
135/135 [==============================] - 0s 517us/step - loss: 0.4855 - acc: 0.8593
Epoch 24/200
135/135 [==============================] - 0s 526us/step - loss: 0.4789 - acc: 0.8667
Epoch 25/200
135/135 [==============================] - 0s 525us/step - loss: 0.4721 - acc: 0.8741
Epoch 26/200
135/135 [==============================] - 0s 515us/step - loss: 0.4633 - acc: 0.8593
Epoch 27/200
135/135 [==============================] - 0s 526us/step - loss: 0.4561 - acc: 0.8444
Epoch 28/200
135/135 [==============================] - 0s 511us/step - loss: 0.4509 - acc: 0.8815
Epoch 29/200
135/135 [=

135/135 [==============================] - 0s 519us/step - loss: 0.2529 - acc: 0.9407
Epoch 102/200
135/135 [==============================] - 0s 524us/step - loss: 0.2510 - acc: 0.9407
Epoch 103/200
135/135 [==============================] - 0s 514us/step - loss: 0.2488 - acc: 0.9333
Epoch 104/200
135/135 [==============================] - 0s 514us/step - loss: 0.2485 - acc: 0.9333
Epoch 105/200
135/135 [==============================] - 0s 516us/step - loss: 0.2441 - acc: 0.9407
Epoch 106/200
135/135 [==============================] - 0s 524us/step - loss: 0.2423 - acc: 0.9407
Epoch 107/200
135/135 [==============================] - 0s 518us/step - loss: 0.2421 - acc: 0.9481
Epoch 108/200
135/135 [==============================] - 0s 523us/step - loss: 0.2404 - acc: 0.9630
Epoch 109/200
135/135 [==============================] - 0s 524us/step - loss: 0.2375 - acc: 0.9481
Epoch 110/200
135/135 [==============================] - 0s 518us/step - loss: 0.2411 - acc: 0.9630
Epoch 111/200


135/135 [==============================] - 0s 515us/step - loss: 0.1497 - acc: 0.9630
Epoch 184/200
135/135 [==============================] - 0s 513us/step - loss: 0.1522 - acc: 0.9630
Epoch 185/200
135/135 [==============================] - 0s 526us/step - loss: 0.1499 - acc: 0.9630
Epoch 186/200
135/135 [==============================] - 0s 524us/step - loss: 0.1481 - acc: 0.9630
Epoch 187/200
135/135 [==============================] - 0s 521us/step - loss: 0.1470 - acc: 0.9630
Epoch 188/200
135/135 [==============================] - 0s 511us/step - loss: 0.1464 - acc: 0.9630
Epoch 189/200
135/135 [==============================] - 0s 513us/step - loss: 0.1462 - acc: 0.9630
Epoch 190/200
135/135 [==============================] - 0s 515us/step - loss: 0.1445 - acc: 0.9630
Epoch 191/200
135/135 [==============================] - 0s 515us/step - loss: 0.1467 - acc: 0.9556
Epoch 192/200
135/135 [==============================] - 0s 521us/step - loss: 0.1422 - acc: 0.9704
Epoch 193/200


135/135 [==============================] - 0s 510us/step - loss: 0.1387 - acc: 0.9778
Epoch 66/200
135/135 [==============================] - 0s 515us/step - loss: 0.1391 - acc: 0.9778
Epoch 67/200
135/135 [==============================] - 0s 521us/step - loss: 0.1364 - acc: 0.9778
Epoch 68/200
135/135 [==============================] - 0s 514us/step - loss: 0.1356 - acc: 0.9778
Epoch 69/200
135/135 [==============================] - 0s 517us/step - loss: 0.1333 - acc: 0.9778
Epoch 70/200
135/135 [==============================] - 0s 513us/step - loss: 0.1335 - acc: 0.9778
Epoch 71/200
135/135 [==============================] - 0s 514us/step - loss: 0.1320 - acc: 0.9778
Epoch 72/200
135/135 [==============================] - 0s 520us/step - loss: 0.1288 - acc: 0.9778
Epoch 73/200
135/135 [==============================] - 0s 512us/step - loss: 0.1297 - acc: 0.9630
Epoch 74/200
135/135 [==============================] - 0s 527us/step - loss: 0.1298 - acc: 0.9778
Epoch 75/200
135/135 [=

135/135 [==============================] - 0s 520us/step - loss: 0.0786 - acc: 0.9704
Epoch 148/200
135/135 [==============================] - 0s 510us/step - loss: 0.0778 - acc: 0.9778
Epoch 149/200
135/135 [==============================] - 0s 523us/step - loss: 0.0770 - acc: 0.9778
Epoch 150/200
135/135 [==============================] - 0s 524us/step - loss: 0.0791 - acc: 0.9704
Epoch 151/200
135/135 [==============================] - 0s 521us/step - loss: 0.0833 - acc: 0.9704
Epoch 152/200
135/135 [==============================] - 0s 515us/step - loss: 0.0785 - acc: 0.9778
Epoch 153/200
135/135 [==============================] - 0s 521us/step - loss: 0.0762 - acc: 0.9778
Epoch 154/200
135/135 [==============================] - 0s 524us/step - loss: 0.0764 - acc: 0.9778
Epoch 155/200
135/135 [==============================] - 0s 513us/step - loss: 0.0766 - acc: 0.9778
Epoch 156/200
135/135 [==============================] - 0s 511us/step - loss: 0.0788 - acc: 0.9778
Epoch 157/200


135/135 [==============================] - 0s 520us/step - loss: 0.5095 - acc: 0.8741
Epoch 29/200
135/135 [==============================] - 0s 520us/step - loss: 0.4979 - acc: 0.8296
Epoch 30/200
135/135 [==============================] - 0s 528us/step - loss: 0.4874 - acc: 0.8370
Epoch 31/200
135/135 [==============================] - 0s 521us/step - loss: 0.4821 - acc: 0.8963
Epoch 32/200
135/135 [==============================] - 0s 522us/step - loss: 0.4687 - acc: 0.9037
Epoch 33/200
135/135 [==============================] - 0s 518us/step - loss: 0.4575 - acc: 0.8741
Epoch 34/200
135/135 [==============================] - 0s 522us/step - loss: 0.4507 - acc: 0.9185
Epoch 35/200
135/135 [==============================] - 0s 519us/step - loss: 0.4421 - acc: 0.9037
Epoch 36/200
135/135 [==============================] - 0s 519us/step - loss: 0.4361 - acc: 0.9333
Epoch 37/200
135/135 [==============================] - 0s 521us/step - loss: 0.4247 - acc: 0.9407
Epoch 38/200
135/135 [=

135/135 [==============================] - 0s 523us/step - loss: 0.1395 - acc: 0.9778
Epoch 111/200
135/135 [==============================] - 0s 522us/step - loss: 0.1367 - acc: 0.9778
Epoch 112/200
135/135 [==============================] - 0s 516us/step - loss: 0.1336 - acc: 0.9926
Epoch 113/200
135/135 [==============================] - 0s 516us/step - loss: 0.1333 - acc: 0.9778
Epoch 114/200
135/135 [==============================] - 0s 517us/step - loss: 0.1333 - acc: 0.9778
Epoch 115/200
135/135 [==============================] - 0s 523us/step - loss: 0.1360 - acc: 0.9778
Epoch 116/200
135/135 [==============================] - 0s 525us/step - loss: 0.1305 - acc: 0.9778
Epoch 117/200
135/135 [==============================] - 0s 531us/step - loss: 0.1297 - acc: 0.9704
Epoch 118/200
135/135 [==============================] - 0s 516us/step - loss: 0.1267 - acc: 0.9852
Epoch 119/200
135/135 [==============================] - 0s 520us/step - loss: 0.1254 - acc: 0.9778
Epoch 120/200


135/135 [==============================] - 0s 523us/step - loss: 0.0743 - acc: 0.9778
Epoch 193/200
135/135 [==============================] - 0s 527us/step - loss: 0.0737 - acc: 0.9778
Epoch 194/200
135/135 [==============================] - 0s 514us/step - loss: 0.0721 - acc: 0.9778
Epoch 195/200
135/135 [==============================] - 0s 515us/step - loss: 0.0724 - acc: 0.9778
Epoch 196/200
135/135 [==============================] - 0s 519us/step - loss: 0.0717 - acc: 0.9778
Epoch 197/200
135/135 [==============================] - 0s 513us/step - loss: 0.0713 - acc: 0.9852
Epoch 198/200
135/135 [==============================] - 0s 517us/step - loss: 0.0724 - acc: 0.9778
Epoch 199/200
135/135 [==============================] - 0s 524us/step - loss: 0.0736 - acc: 0.9778
Epoch 200/200
15/15 [==============================] - 1s 89ms/step
Epoch 1/200
135/135 [==============================] - 3s 24ms/step - loss: 2.7527 - acc: 0.3259
Epoch 2/200
135/135 [============================

135/135 [==============================] - 0s 521us/step - loss: 0.3018 - acc: 0.9704
Epoch 75/200
135/135 [==============================] - 0s 519us/step - loss: 0.2987 - acc: 0.9704
Epoch 76/200
135/135 [==============================] - 0s 529us/step - loss: 0.2952 - acc: 0.9704
Epoch 77/200
135/135 [==============================] - 0s 513us/step - loss: 0.2912 - acc: 0.9704
Epoch 78/200
135/135 [==============================] - 0s 527us/step - loss: 0.2891 - acc: 0.9704
Epoch 79/200
135/135 [==============================] - 0s 531us/step - loss: 0.2856 - acc: 0.9704
Epoch 80/200
135/135 [==============================] - 0s 519us/step - loss: 0.2819 - acc: 0.9704
Epoch 81/200
135/135 [==============================] - 0s 518us/step - loss: 0.2789 - acc: 0.9704
Epoch 82/200
135/135 [==============================] - 0s 524us/step - loss: 0.2754 - acc: 0.9704
Epoch 83/200
135/135 [==============================] - 0s 525us/step - loss: 0.2729 - acc: 0.9704
Epoch 84/200
135/135 [=

135/135 [==============================] - 0s 523us/step - loss: 0.1322 - acc: 0.9852
Epoch 157/200
135/135 [==============================] - 0s 532us/step - loss: 0.1279 - acc: 0.9852
Epoch 158/200
135/135 [==============================] - 0s 530us/step - loss: 0.1263 - acc: 0.9852
Epoch 159/200
135/135 [==============================] - 0s 523us/step - loss: 0.1260 - acc: 0.9852
Epoch 160/200
135/135 [==============================] - 0s 528us/step - loss: 0.1252 - acc: 0.9852
Epoch 161/200
135/135 [==============================] - 0s 531us/step - loss: 0.1244 - acc: 0.9852
Epoch 162/200
135/135 [==============================] - 0s 520us/step - loss: 0.1242 - acc: 0.9852
Epoch 163/200
135/135 [==============================] - 0s 530us/step - loss: 0.1248 - acc: 0.9778
Epoch 164/200
135/135 [==============================] - 0s 518us/step - loss: 0.1212 - acc: 0.9778
Epoch 165/200
135/135 [==============================] - 0s 523us/step - loss: 0.1200 - acc: 0.9852
Epoch 166/200


Epoch 38/200
135/135 [==============================] - 0s 522us/step - loss: 0.3966 - acc: 0.9333
Epoch 39/200
135/135 [==============================] - 0s 536us/step - loss: 0.3925 - acc: 0.9407
Epoch 40/200
135/135 [==============================] - 0s 544us/step - loss: 0.3865 - acc: 0.9778
Epoch 41/200
135/135 [==============================] - 0s 534us/step - loss: 0.3815 - acc: 0.9630
Epoch 42/200
135/135 [==============================] - 0s 525us/step - loss: 0.3791 - acc: 0.9407
Epoch 43/200
135/135 [==============================] - 0s 534us/step - loss: 0.3739 - acc: 0.9556
Epoch 44/200
135/135 [==============================] - 0s 529us/step - loss: 0.3697 - acc: 0.9630
Epoch 45/200
135/135 [==============================] - 0s 525us/step - loss: 0.3668 - acc: 0.9407
Epoch 46/200
135/135 [==============================] - 0s 550us/step - loss: 0.3616 - acc: 0.9704
Epoch 47/200
135/135 [==============================] - 0s 528us/step - loss: 0.3585 - acc: 0.9556
Epoch 48/2

135/135 [==============================] - 0s 525us/step - loss: 0.1701 - acc: 0.9704
Epoch 121/200
135/135 [==============================] - 0s 530us/step - loss: 0.1672 - acc: 0.9778
Epoch 122/200
135/135 [==============================] - 0s 522us/step - loss: 0.1642 - acc: 0.9704
Epoch 123/200
135/135 [==============================] - 0s 528us/step - loss: 0.1642 - acc: 0.9704
Epoch 124/200
135/135 [==============================] - 0s 528us/step - loss: 0.1626 - acc: 0.9852
Epoch 125/200
135/135 [==============================] - 0s 531us/step - loss: 0.1598 - acc: 0.9778
Epoch 126/200
135/135 [==============================] - 0s 525us/step - loss: 0.1594 - acc: 0.9704
Epoch 127/200
135/135 [==============================] - 0s 539us/step - loss: 0.1584 - acc: 0.9778
Epoch 128/200
135/135 [==============================] - 0s 528us/step - loss: 0.1572 - acc: 0.9704
Epoch 129/200
135/135 [==============================] - 0s 530us/step - loss: 0.1596 - acc: 0.9630
Epoch 130/200


135/135 [==============================] - 3s 25ms/step - loss: 2.1485 - acc: 0.3259
Epoch 2/200
135/135 [==============================] - 0s 518us/step - loss: 1.3949 - acc: 0.3852
Epoch 3/200
135/135 [==============================] - 0s 522us/step - loss: 0.9182 - acc: 0.7111
Epoch 4/200
135/135 [==============================] - 0s 516us/step - loss: 0.8000 - acc: 0.6815
Epoch 5/200
135/135 [==============================] - 0s 529us/step - loss: 0.7938 - acc: 0.6741
Epoch 6/200
135/135 [==============================] - 0s 525us/step - loss: 0.7739 - acc: 0.6963
Epoch 7/200
135/135 [==============================] - 0s 518us/step - loss: 0.7535 - acc: 0.7037
Epoch 8/200
135/135 [==============================] - 0s 516us/step - loss: 0.7377 - acc: 0.6889
Epoch 9/200
135/135 [==============================] - 0s 524us/step - loss: 0.7205 - acc: 0.6815
Epoch 10/200
135/135 [==============================] - 0s 520us/step - loss: 0.7070 - acc: 0.7407
Epoch 11/200
135/135 [==========

Epoch 84/200
135/135 [==============================] - 0s 521us/step - loss: 0.2397 - acc: 0.9630
Epoch 85/200
135/135 [==============================] - 0s 526us/step - loss: 0.2370 - acc: 0.9481
Epoch 86/200
135/135 [==============================] - 0s 529us/step - loss: 0.2350 - acc: 0.9481
Epoch 87/200
135/135 [==============================] - 0s 518us/step - loss: 0.2331 - acc: 0.9630
Epoch 88/200
135/135 [==============================] - 0s 517us/step - loss: 0.2321 - acc: 0.9556
Epoch 89/200
135/135 [==============================] - 0s 532us/step - loss: 0.2285 - acc: 0.9556
Epoch 90/200
135/135 [==============================] - 0s 519us/step - loss: 0.2261 - acc: 0.9630
Epoch 91/200
135/135 [==============================] - 0s 521us/step - loss: 0.2251 - acc: 0.9556
Epoch 92/200
135/135 [==============================] - 0s 533us/step - loss: 0.2225 - acc: 0.9556
Epoch 93/200
135/135 [==============================] - 0s 520us/step - loss: 0.2196 - acc: 0.9630
Epoch 94/2

135/135 [==============================] - 0s 529us/step - loss: 0.1282 - acc: 0.9630
Epoch 167/200
135/135 [==============================] - 0s 540us/step - loss: 0.1284 - acc: 0.9630
Epoch 168/200
135/135 [==============================] - 0s 524us/step - loss: 0.1272 - acc: 0.9630
Epoch 169/200
135/135 [==============================] - 0s 524us/step - loss: 0.1256 - acc: 0.9778
Epoch 170/200
135/135 [==============================] - 0s 522us/step - loss: 0.1278 - acc: 0.9630
Epoch 171/200
135/135 [==============================] - 0s 519us/step - loss: 0.1245 - acc: 0.9556
Epoch 172/200
135/135 [==============================] - 0s 530us/step - loss: 0.1277 - acc: 0.9630
Epoch 173/200
135/135 [==============================] - 0s 527us/step - loss: 0.1238 - acc: 0.9704
Epoch 174/200
135/135 [==============================] - 0s 526us/step - loss: 0.1247 - acc: 0.9704
Epoch 175/200
135/135 [==============================] - 0s 526us/step - loss: 0.1231 - acc: 0.9630
Epoch 176/200


In [103]:
X.shape

(150, 4)